### ISSUE TITLE
Migration from API v1 to v2.0.0

### ISSUE THREAD

**Issue by godismyjudge95** [friday/ulauncher-hash2#2]
Ulauncher just released a new version and it broke this extension.
See here:
https://mailchi.mp/fbb4b54c426a/ulauncher-is-migrating-to-python-3-changes-to-extension-api-and-more

And here:
http://docs.ulauncher.io/en/latest/extensions/migration.html

**Comment by friday** [comment]
I know. I was probably the first one to migrate an extension ;) It's not officially released yet though. You really shouldn't be using it yet.

**Comment by godismyjudge95** [comment]
@friday yeah, through some weird event I accidentally got updated to the v5.x version.  I figured I might try to help out the extensions that I use in the migration process.

**Comment by friday** [comment]
I committed without testing since up/downgrading is a bit of a hassle on my distro (https://github.com/Ulauncher/Ulauncher/issues/385). It may work now. If not, fixing it in the v5-branch should be fairly simple I think.

Unsure utf-8 works with the current implementation even if it does work. Might need to lose `.encode('utf-8')`.

Also see https://github.com/Ulauncher/Ulauncher/issues/384 (why you got the beta version probably)

**Comment by friday** [comment]
Unsure utf-8 works with the current implementation even if it does work. Might need to lose `.encode('utf-8')`.

**Comment by friday** [comment]
Fixed (verified this time).
As an unintended side effect of using Python 3, the convenient list of common algos is now gone. Instead a longer one is used. So the keyword `hash` is less useful now. Could possibly add a whitelist or hard code a list.
